### ISSUE TITLE
Dependency Optimization manifest key incorrect

### ISSUE THREAD

**Issue by paul-hansen** [TimJentzsch/cargo-bavy#11]
Using cargo-bavy it generates this:
``` toml
["profile.dev"]
opt-level = 1

["profile.dev.package.\"*\""]
opt-level = 3
```
Which produces the following warnings: 
```
warning: unused manifest key: profile.dev
warning: unused manifest key: profile.dev.package."*"
```

It should be:
``` toml
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
```
